/*******************************************************************************
Copyright (C) Marvell International Ltd. and its affiliates

This software file (the "File") is owned and distributed by Marvell
International Ltd. and/or its affiliates ("Marvell") under the following
alternative licensing terms.  Once you have made an election to distribute the
File under one of the following license alternatives, please (i) delete this
introductory statement regarding license alternatives, (ii) delete the two
license alternatives that you have not elected to use and (iii) preserve the
Marvell copyright notice above.

********************************************************************************
Marvell GPL License Option

If you received this File from Marvell, you may opt to use, redistribute and/or
modify this File in accordance with the terms and conditions of the General
Public License Version 2, June 1991 (the "GPL License"), a copy of which is
available along with the File in the license.txt file or by writing to the Free
Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 or
on the worldwide web at http://www.gnu.org/licenses/gpl.txt.

THE FILE IS DISTRIBUTED AS-IS, WITHOUT WARRANTY OF ANY KIND, AND THE IMPLIED
WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY
DISCLAIMED.  The GPL License provides additional details about this warranty
disclaimer.
*******************************************************************************/

/************************************
 * AUTOGENERATED FILE - DO NOT EDIT *
*************************************/


#include <linux/pci.h>
#include "inno_cmipd_v2.h"
int cfx_v2_init(cfx_v2_t* cmp)
{
    if (!cmp) {
        return -1;
    }
    memset(cmp, 0, sizeof(cfx_v2_t));
    /* Initialize ipd_f0 */
    cmp->ipd_f0.num_val = 1;
    cmp->ipd_f0.bit_width = 1;
    cmp->ipd_f0.bit_offset = 0;
    /* Initialize ipd_f1 */
    cmp->ipd_f1.num_val = 1;
    cmp->ipd_f1.bit_width = 3;
    cmp->ipd_f1.bit_offset = 1;
    /* Initialize ipd_f2 */
    cmp->ipd_f2.num_val = 1;
    cmp->ipd_f2.bit_width = 7;
    cmp->ipd_f2.bit_offset = 4;
    /* Initialize ipd_f3 */
    cmp->ipd_f3.num_val = 1;
    cmp->ipd_f3.bit_width = 3;
    cmp->ipd_f3.bit_offset = 11;
    /* Initialize ipd_f4 */
    cmp->ipd_f4.num_val = 1;
    cmp->ipd_f4.bit_width = 1;
    cmp->ipd_f4.bit_offset = 14;
    /* Initialize ipd_f5 */
    cmp->ipd_f5.num_val = 1;
    cmp->ipd_f5.bit_width = 1;
    cmp->ipd_f5.bit_offset = 15;
    /* Initialize ipd_f6 */
    cmp->ipd_f6.num_val = 1;
    cmp->ipd_f6.bit_width = 7;
    cmp->ipd_f6.bit_offset = 16;
    /* Initialize ipd_f7 */
    cmp->ipd_f7.num_val = 1;
    cmp->ipd_f7.bit_width = 1;
    cmp->ipd_f7.bit_offset = 23;
    /* Initialize ipd_f8 */
    cmp->ipd_f8.num_val = 1;
    cmp->ipd_f8.bit_width = 1;
    cmp->ipd_f8.bit_offset = 24;
    /* Initialize ipd_f9 */
    cmp->ipd_f9.num_val = 1;
    cmp->ipd_f9.bit_width = 4;
    cmp->ipd_f9.bit_offset = 25;
    /* Initialize ipd_f10 */
    cmp->ipd_f10.num_val = 1;
    cmp->ipd_f10.bit_width = 11;
    cmp->ipd_f10.bit_offset = 29;
    /* Initialize ipd_f11 */
    cmp->ipd_f11.num_val = 1;
    cmp->ipd_f11.bit_width = 1;
    cmp->ipd_f11.bit_offset = 40;
    /* Initialize ipd_f12 */
    cmp->ipd_f12.num_val = 1;
    cmp->ipd_f12.bit_width = 13;
    cmp->ipd_f12.bit_offset = 41;
    /* Initialize ipd_f13 */
    cmp->ipd_f13.num_val = 1;
    cmp->ipd_f13.bit_width = 6;
    cmp->ipd_f13.bit_offset = 54;
    /* Initialize ipd_f14 */
    cmp->ipd_f14.num_val = 1;
    cmp->ipd_f14.bit_width = 3;
    cmp->ipd_f14.bit_offset = 60;
    /* Initialize ipd_f15 */
    cmp->ipd_f15.num_val = 1;
    cmp->ipd_f15.bit_width = 3;
    cmp->ipd_f15.bit_offset = 63;
    /* Initialize ipd_f16 */
    cmp->ipd_f16.num_val = 1;
    cmp->ipd_f16.bit_width = 6;
    cmp->ipd_f16.bit_offset = 66;
    return 0;
}

int cfx_v2_pack(cfx_v2_t* cmp, uint8_t * bm)
{
    uint32_t w_id=0, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    PACK_V2_FIELD(cmp->ipd_f0, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f1, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f2, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f3, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f4, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f5, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f6, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f7, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f8, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f9, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f10, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f11, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f12, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f13, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f14, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f15, w_id, b_id, bm, 1);
    PACK_V2_FIELD(cmp->ipd_f16, w_id, b_id, bm, 1);
    return 0;
}

int cfx_v2_unpack(cfx_v2_t* cmp, uint8_t * bm)
{
    uint32_t w_id=0, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    UNPACK_V2_FIELD(cmp->ipd_f0, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f1, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f2, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f3, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f4, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f5, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f6, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f7, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f8, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f9, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f10, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f11, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f12, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f13, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f14, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f15, w_id, b_id, bm, 1);
    UNPACK_V2_FIELD(cmp->ipd_f16, w_id, b_id, bm, 1);
    return 0;
}

int cfx_v2_clear_fields(cfx_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd_f0.num_val; i++) {
        cmp->ipd_f0.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f1.num_val; i++) {
        cmp->ipd_f1.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f2.num_val; i++) {
        cmp->ipd_f2.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f3.num_val; i++) {
        cmp->ipd_f3.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f4.num_val; i++) {
        cmp->ipd_f4.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f5.num_val; i++) {
        cmp->ipd_f5.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f6.num_val; i++) {
        cmp->ipd_f6.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f7.num_val; i++) {
        cmp->ipd_f7.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f8.num_val; i++) {
        cmp->ipd_f8.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f9.num_val; i++) {
        cmp->ipd_f9.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f10.num_val; i++) {
        cmp->ipd_f10.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f11.num_val; i++) {
        cmp->ipd_f11.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f12.num_val; i++) {
        cmp->ipd_f12.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f13.num_val; i++) {
        cmp->ipd_f13.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f14.num_val; i++) {
        cmp->ipd_f14.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f15.num_val; i++) {
        cmp->ipd_f15.value[i] = 0;
    }
    for (i=0; i < cmp->ipd_f16.num_val; i++) {
        cmp->ipd_f16.value[i] = 0;
    }
    return 0;
}

int cfx_v2_set_fields(cfx_v2_fields_t* cmf, cfx_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd_f0.num_val; i++) {
        cmp->ipd_f0.value[i] = cmf->ipd_f0[i];
    }
    for (i=0; i < cmp->ipd_f1.num_val; i++) {
        cmp->ipd_f1.value[i] = cmf->ipd_f1[i];
    }
    for (i=0; i < cmp->ipd_f2.num_val; i++) {
        cmp->ipd_f2.value[i] = cmf->ipd_f2[i];
    }
    for (i=0; i < cmp->ipd_f3.num_val; i++) {
        cmp->ipd_f3.value[i] = cmf->ipd_f3[i];
    }
    for (i=0; i < cmp->ipd_f4.num_val; i++) {
        cmp->ipd_f4.value[i] = cmf->ipd_f4[i];
    }
    for (i=0; i < cmp->ipd_f5.num_val; i++) {
        cmp->ipd_f5.value[i] = cmf->ipd_f5[i];
    }
    for (i=0; i < cmp->ipd_f6.num_val; i++) {
        cmp->ipd_f6.value[i] = cmf->ipd_f6[i];
    }
    for (i=0; i < cmp->ipd_f7.num_val; i++) {
        cmp->ipd_f7.value[i] = cmf->ipd_f7[i];
    }
    for (i=0; i < cmp->ipd_f8.num_val; i++) {
        cmp->ipd_f8.value[i] = cmf->ipd_f8[i];
    }
    for (i=0; i < cmp->ipd_f9.num_val; i++) {
        cmp->ipd_f9.value[i] = cmf->ipd_f9[i];
    }
    for (i=0; i < cmp->ipd_f10.num_val; i++) {
        cmp->ipd_f10.value[i] = cmf->ipd_f10[i];
    }
    for (i=0; i < cmp->ipd_f11.num_val; i++) {
        cmp->ipd_f11.value[i] = cmf->ipd_f11[i];
    }
    for (i=0; i < cmp->ipd_f12.num_val; i++) {
        cmp->ipd_f12.value[i] = cmf->ipd_f12[i];
    }
    for (i=0; i < cmp->ipd_f13.num_val; i++) {
        cmp->ipd_f13.value[i] = cmf->ipd_f13[i];
    }
    for (i=0; i < cmp->ipd_f14.num_val; i++) {
        cmp->ipd_f14.value[i] = cmf->ipd_f14[i];
    }
    for (i=0; i < cmp->ipd_f15.num_val; i++) {
        cmp->ipd_f15.value[i] = cmf->ipd_f15[i];
    }
    for (i=0; i < cmp->ipd_f16.num_val; i++) {
        cmp->ipd_f16.value[i] = cmf->ipd_f16[i];
    }
    return 0;
}

int cfx_v2_get_fields(cfx_v2_fields_t* cmf, cfx_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd_f0.num_val; i++) {
        cmf->ipd_f0[i] = cmp->ipd_f0.value[i];
    }
    for (i=0; i < cmp->ipd_f1.num_val; i++) {
        cmf->ipd_f1[i] = cmp->ipd_f1.value[i];
    }
    for (i=0; i < cmp->ipd_f2.num_val; i++) {
        cmf->ipd_f2[i] = cmp->ipd_f2.value[i];
    }
    for (i=0; i < cmp->ipd_f3.num_val; i++) {
        cmf->ipd_f3[i] = cmp->ipd_f3.value[i];
    }
    for (i=0; i < cmp->ipd_f4.num_val; i++) {
        cmf->ipd_f4[i] = cmp->ipd_f4.value[i];
    }
    for (i=0; i < cmp->ipd_f5.num_val; i++) {
        cmf->ipd_f5[i] = cmp->ipd_f5.value[i];
    }
    for (i=0; i < cmp->ipd_f6.num_val; i++) {
        cmf->ipd_f6[i] = cmp->ipd_f6.value[i];
    }
    for (i=0; i < cmp->ipd_f7.num_val; i++) {
        cmf->ipd_f7[i] = cmp->ipd_f7.value[i];
    }
    for (i=0; i < cmp->ipd_f8.num_val; i++) {
        cmf->ipd_f8[i] = cmp->ipd_f8.value[i];
    }
    for (i=0; i < cmp->ipd_f9.num_val; i++) {
        cmf->ipd_f9[i] = cmp->ipd_f9.value[i];
    }
    for (i=0; i < cmp->ipd_f10.num_val; i++) {
        cmf->ipd_f10[i] = cmp->ipd_f10.value[i];
    }
    for (i=0; i < cmp->ipd_f11.num_val; i++) {
        cmf->ipd_f11[i] = cmp->ipd_f11.value[i];
    }
    for (i=0; i < cmp->ipd_f12.num_val; i++) {
        cmf->ipd_f12[i] = cmp->ipd_f12.value[i];
    }
    for (i=0; i < cmp->ipd_f13.num_val; i++) {
        cmf->ipd_f13[i] = cmp->ipd_f13.value[i];
    }
    for (i=0; i < cmp->ipd_f14.num_val; i++) {
        cmf->ipd_f14[i] = cmp->ipd_f14.value[i];
    }
    for (i=0; i < cmp->ipd_f15.num_val; i++) {
        cmf->ipd_f15[i] = cmp->ipd_f15.value[i];
    }
    for (i=0; i < cmp->ipd_f16.num_val; i++) {
        cmf->ipd_f16[i] = cmp->ipd_f16.value[i];
    }
    return 0;
}

cfx_v2_t g_cfx_v2 = {
    {{0}, 1, 1, 0},
    {{0}, 1, 3, 1},
    {{0}, 1, 7, 4},
    {{0}, 1, 3, 11},
    {{0}, 1, 1, 14},
    {{0}, 1, 1, 15},
    {{0}, 1, 7, 16},
    {{0}, 1, 1, 23},
    {{0}, 1, 1, 24},
    {{0}, 1, 4, 25},
    {{0}, 1, 11, 29},
    {{0}, 1, 1, 40},
    {{0}, 1, 13, 41},
    {{0}, 1, 6, 54},
    {{0}, 1, 3, 60},
    {{0}, 1, 3, 63},
    {{0}, 1, 6, 66},
};

cfx_v2_func_t g_func_cfx_v2 = {
    cfx_v2_pack,
    cfx_v2_unpack,
    cfx_v2_set_fields,
    cfx_v2_get_fields,
};

int pf2_1_v2_init(pf2_1_v2_t* cmp)
{
    if (!cmp) {
        return -1;
    }
    memset(cmp, 0, sizeof(pf2_1_v2_t));
    /* Initialize ipd2_f0 */
    cmp->ipd2_f0.num_val = 1;
    cmp->ipd2_f0.bit_width = 9;
    cmp->ipd2_f0.bit_offset = 0;
    /* Initialize ipd2_f1 */
    cmp->ipd2_f1.num_val = 1;
    cmp->ipd2_f1.bit_width = 16;
    cmp->ipd2_f1.bit_offset = 9;
    /* Initialize ipd2_f4 */
    cmp->ipd2_f4.num_val = 4;
    cmp->ipd2_f4.bit_width = 128;
    cmp->ipd2_f4.bit_offset = 25;
    /* Initialize ipd2_f5 */
    cmp->ipd2_f5.num_val = 1;
    cmp->ipd2_f5.bit_width = 8;
    cmp->ipd2_f5.bit_offset = 153;
    /* Initialize ipd2_f6 */
    cmp->ipd2_f6.num_val = 1;
    cmp->ipd2_f6.bit_width = 2;
    cmp->ipd2_f6.bit_offset = 161;
    return 0;
}

int pf2_1_v2_pack(pf2_1_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=0, w_id=39, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    PACK_V2_FIELD(cmp->ipd2_f0, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f1, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f4, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f5, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f6, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf2_1_v2_unpack(pf2_1_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=0, w_id=39, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    UNPACK_V2_FIELD(cmp->ipd2_f0, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f1, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f4, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f5, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f6, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf2_1_v2_clear_fields(pf2_1_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd2_f0.num_val; i++) {
        cmp->ipd2_f0.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f1.num_val; i++) {
        cmp->ipd2_f1.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f4.num_val; i++) {
        cmp->ipd2_f4.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f5.num_val; i++) {
        cmp->ipd2_f5.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f6.num_val; i++) {
        cmp->ipd2_f6.value[i] = 0;
    }
    return 0;
}

int pf2_1_v2_set_fields(pf2_1_v2_fields_t* cmf, pf2_1_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd2_f0.num_val; i++) {
        cmp->ipd2_f0.value[i] = cmf->ipd2_f0[i];
    }
    for (i=0; i < cmp->ipd2_f1.num_val; i++) {
        cmp->ipd2_f1.value[i] = cmf->ipd2_f1[i];
    }
    for (i=0; i < cmp->ipd2_f4.num_val; i++) {
        cmp->ipd2_f4.value[i] = cmf->ipd2_f4[i];
    }
    for (i=0; i < cmp->ipd2_f5.num_val; i++) {
        cmp->ipd2_f5.value[i] = cmf->ipd2_f5[i];
    }
    for (i=0; i < cmp->ipd2_f6.num_val; i++) {
        cmp->ipd2_f6.value[i] = cmf->ipd2_f6[i];
    }
    return 0;
}

int pf2_1_v2_get_fields(pf2_1_v2_fields_t* cmf, pf2_1_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd2_f0.num_val; i++) {
        cmf->ipd2_f0[i] = cmp->ipd2_f0.value[i];
    }
    for (i=0; i < cmp->ipd2_f1.num_val; i++) {
        cmf->ipd2_f1[i] = cmp->ipd2_f1.value[i];
    }
    for (i=0; i < cmp->ipd2_f4.num_val; i++) {
        cmf->ipd2_f4[i] = cmp->ipd2_f4.value[i];
    }
    for (i=0; i < cmp->ipd2_f5.num_val; i++) {
        cmf->ipd2_f5[i] = cmp->ipd2_f5.value[i];
    }
    for (i=0; i < cmp->ipd2_f6.num_val; i++) {
        cmf->ipd2_f6[i] = cmp->ipd2_f6.value[i];
    }
    return 0;
}

pf2_1_v2_t g_pf2_1_v2 = {
    {{0}, 1, 9, 0},
    {{0}, 1, 16, 9},
    {{0}, 4, 128, 25},
    {{0}, 1, 8, 153},
    {{0}, 1, 2, 161},
};

pf2_1_v2_func_t g_func_pf2_1_v2 = {
    pf2_1_v2_pack,
    pf2_1_v2_unpack,
    pf2_1_v2_set_fields,
    pf2_1_v2_get_fields,
};

int pf2_2_v2_init(pf2_2_v2_t* cmp)
{
    if (!cmp) {
        return -1;
    }
    memset(cmp, 0, sizeof(pf2_2_v2_t));
    /* Initialize ipd2_f0 */
    cmp->ipd2_f0.num_val = 1;
    cmp->ipd2_f0.bit_width = 9;
    cmp->ipd2_f0.bit_offset = 0;
    /* Initialize ipd2_f1 */
    cmp->ipd2_f1.num_val = 1;
    cmp->ipd2_f1.bit_width = 16;
    cmp->ipd2_f1.bit_offset = 9;
    /* Initialize ipd2_f2 */
    cmp->ipd2_f2.num_val = 1;
    cmp->ipd2_f2.bit_width = 8;
    cmp->ipd2_f2.bit_offset = 25;
    /* Initialize ipd2_f3 */
    cmp->ipd2_f3.num_val = 1;
    cmp->ipd2_f3.bit_width = 8;
    cmp->ipd2_f3.bit_offset = 33;
    /* Initialize ipd2_f4 */
    cmp->ipd2_f4.num_val = 3;
    cmp->ipd2_f4.bit_width = 96;
    cmp->ipd2_f4.bit_offset = 41;
    /* Initialize ipd2_f5 */
    cmp->ipd2_f5.num_val = 1;
    cmp->ipd2_f5.bit_width = 8;
    cmp->ipd2_f5.bit_offset = 137;
    /* Initialize ipd2_f6 */
    cmp->ipd2_f6.num_val = 1;
    cmp->ipd2_f6.bit_width = 2;
    cmp->ipd2_f6.bit_offset = 145;
    return 0;
}

int pf2_2_v2_pack(pf2_2_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=0, w_id=39, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    PACK_V2_FIELD(cmp->ipd2_f0, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f1, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f2, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f3, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f4, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f5, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f6, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf2_2_v2_unpack(pf2_2_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=0, w_id=39, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    UNPACK_V2_FIELD(cmp->ipd2_f0, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f1, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f2, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f3, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f4, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f5, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f6, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf2_2_v2_clear_fields(pf2_2_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd2_f0.num_val; i++) {
        cmp->ipd2_f0.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f1.num_val; i++) {
        cmp->ipd2_f1.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f2.num_val; i++) {
        cmp->ipd2_f2.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f3.num_val; i++) {
        cmp->ipd2_f3.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f4.num_val; i++) {
        cmp->ipd2_f4.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f5.num_val; i++) {
        cmp->ipd2_f5.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f6.num_val; i++) {
        cmp->ipd2_f6.value[i] = 0;
    }
    return 0;
}

int pf2_2_v2_set_fields(pf2_2_v2_fields_t* cmf, pf2_2_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd2_f0.num_val; i++) {
        cmp->ipd2_f0.value[i] = cmf->ipd2_f0[i];
    }
    for (i=0; i < cmp->ipd2_f1.num_val; i++) {
        cmp->ipd2_f1.value[i] = cmf->ipd2_f1[i];
    }
    for (i=0; i < cmp->ipd2_f2.num_val; i++) {
        cmp->ipd2_f2.value[i] = cmf->ipd2_f2[i];
    }
    for (i=0; i < cmp->ipd2_f3.num_val; i++) {
        cmp->ipd2_f3.value[i] = cmf->ipd2_f3[i];
    }
    for (i=0; i < cmp->ipd2_f4.num_val; i++) {
        cmp->ipd2_f4.value[i] = cmf->ipd2_f4[i];
    }
    for (i=0; i < cmp->ipd2_f5.num_val; i++) {
        cmp->ipd2_f5.value[i] = cmf->ipd2_f5[i];
    }
    for (i=0; i < cmp->ipd2_f6.num_val; i++) {
        cmp->ipd2_f6.value[i] = cmf->ipd2_f6[i];
    }
    return 0;
}

int pf2_2_v2_get_fields(pf2_2_v2_fields_t* cmf, pf2_2_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd2_f0.num_val; i++) {
        cmf->ipd2_f0[i] = cmp->ipd2_f0.value[i];
    }
    for (i=0; i < cmp->ipd2_f1.num_val; i++) {
        cmf->ipd2_f1[i] = cmp->ipd2_f1.value[i];
    }
    for (i=0; i < cmp->ipd2_f2.num_val; i++) {
        cmf->ipd2_f2[i] = cmp->ipd2_f2.value[i];
    }
    for (i=0; i < cmp->ipd2_f3.num_val; i++) {
        cmf->ipd2_f3[i] = cmp->ipd2_f3.value[i];
    }
    for (i=0; i < cmp->ipd2_f4.num_val; i++) {
        cmf->ipd2_f4[i] = cmp->ipd2_f4.value[i];
    }
    for (i=0; i < cmp->ipd2_f5.num_val; i++) {
        cmf->ipd2_f5[i] = cmp->ipd2_f5.value[i];
    }
    for (i=0; i < cmp->ipd2_f6.num_val; i++) {
        cmf->ipd2_f6[i] = cmp->ipd2_f6.value[i];
    }
    return 0;
}

pf2_2_v2_t g_pf2_2_v2 = {
    {{0}, 1, 9, 0},
    {{0}, 1, 16, 9},
    {{0}, 1, 8, 25},
    {{0}, 1, 8, 33},
    {{0}, 3, 96, 41},
    {{0}, 1, 8, 137},
    {{0}, 1, 2, 145},
};

pf2_2_v2_func_t g_func_pf2_2_v2 = {
    pf2_2_v2_pack,
    pf2_2_v2_unpack,
    pf2_2_v2_set_fields,
    pf2_2_v2_get_fields,
};

int pf2_3_v2_init(pf2_3_v2_t* cmp)
{
    if (!cmp) {
        return -1;
    }
    memset(cmp, 0, sizeof(pf2_3_v2_t));
    /* Initialize ipd2_f0 */
    cmp->ipd2_f0.num_val = 1;
    cmp->ipd2_f0.bit_width = 9;
    cmp->ipd2_f0.bit_offset = 0;
    /* Initialize ipd2_f1 */
    cmp->ipd2_f1.num_val = 1;
    cmp->ipd2_f1.bit_width = 16;
    cmp->ipd2_f1.bit_offset = 9;
    /* Initialize ipd2_f2 */
    cmp->ipd2_f2.num_val = 1;
    cmp->ipd2_f2.bit_width = 8;
    cmp->ipd2_f2.bit_offset = 25;
    /* Initialize ipd2_f3 */
    cmp->ipd2_f3.num_val = 1;
    cmp->ipd2_f3.bit_width = 8;
    cmp->ipd2_f3.bit_offset = 33;
    /* Initialize ipd2_f4 */
    cmp->ipd2_f4.num_val = 2;
    cmp->ipd2_f4.bit_width = 48;
    cmp->ipd2_f4.bit_offset = 41;
    /* Initialize ipd2_f5 */
    cmp->ipd2_f5.num_val = 1;
    cmp->ipd2_f5.bit_width = 8;
    cmp->ipd2_f5.bit_offset = 89;
    /* Initialize ipd2_f6 */
    cmp->ipd2_f6.num_val = 1;
    cmp->ipd2_f6.bit_width = 2;
    cmp->ipd2_f6.bit_offset = 97;
    return 0;
}

int pf2_3_v2_pack(pf2_3_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=0, w_id=39, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    PACK_V2_FIELD(cmp->ipd2_f0, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f1, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f2, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f3, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f4, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f5, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd2_f6, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf2_3_v2_unpack(pf2_3_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=0, w_id=39, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    UNPACK_V2_FIELD(cmp->ipd2_f0, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f1, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f2, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f3, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f4, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f5, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd2_f6, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf2_3_v2_clear_fields(pf2_3_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd2_f0.num_val; i++) {
        cmp->ipd2_f0.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f1.num_val; i++) {
        cmp->ipd2_f1.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f2.num_val; i++) {
        cmp->ipd2_f2.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f3.num_val; i++) {
        cmp->ipd2_f3.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f4.num_val; i++) {
        cmp->ipd2_f4.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f5.num_val; i++) {
        cmp->ipd2_f5.value[i] = 0;
    }
    for (i=0; i < cmp->ipd2_f6.num_val; i++) {
        cmp->ipd2_f6.value[i] = 0;
    }
    return 0;
}

int pf2_3_v2_set_fields(pf2_3_v2_fields_t* cmf, pf2_3_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd2_f0.num_val; i++) {
        cmp->ipd2_f0.value[i] = cmf->ipd2_f0[i];
    }
    for (i=0; i < cmp->ipd2_f1.num_val; i++) {
        cmp->ipd2_f1.value[i] = cmf->ipd2_f1[i];
    }
    for (i=0; i < cmp->ipd2_f2.num_val; i++) {
        cmp->ipd2_f2.value[i] = cmf->ipd2_f2[i];
    }
    for (i=0; i < cmp->ipd2_f3.num_val; i++) {
        cmp->ipd2_f3.value[i] = cmf->ipd2_f3[i];
    }
    for (i=0; i < cmp->ipd2_f4.num_val; i++) {
        cmp->ipd2_f4.value[i] = cmf->ipd2_f4[i];
    }
    for (i=0; i < cmp->ipd2_f5.num_val; i++) {
        cmp->ipd2_f5.value[i] = cmf->ipd2_f5[i];
    }
    for (i=0; i < cmp->ipd2_f6.num_val; i++) {
        cmp->ipd2_f6.value[i] = cmf->ipd2_f6[i];
    }
    return 0;
}

int pf2_3_v2_get_fields(pf2_3_v2_fields_t* cmf, pf2_3_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd2_f0.num_val; i++) {
        cmf->ipd2_f0[i] = cmp->ipd2_f0.value[i];
    }
    for (i=0; i < cmp->ipd2_f1.num_val; i++) {
        cmf->ipd2_f1[i] = cmp->ipd2_f1.value[i];
    }
    for (i=0; i < cmp->ipd2_f2.num_val; i++) {
        cmf->ipd2_f2[i] = cmp->ipd2_f2.value[i];
    }
    for (i=0; i < cmp->ipd2_f3.num_val; i++) {
        cmf->ipd2_f3[i] = cmp->ipd2_f3.value[i];
    }
    for (i=0; i < cmp->ipd2_f4.num_val; i++) {
        cmf->ipd2_f4[i] = cmp->ipd2_f4.value[i];
    }
    for (i=0; i < cmp->ipd2_f5.num_val; i++) {
        cmf->ipd2_f5[i] = cmp->ipd2_f5.value[i];
    }
    for (i=0; i < cmp->ipd2_f6.num_val; i++) {
        cmf->ipd2_f6[i] = cmp->ipd2_f6.value[i];
    }
    return 0;
}

pf2_3_v2_t g_pf2_3_v2 = {
    {{0}, 1, 9, 0},
    {{0}, 1, 16, 9},
    {{0}, 1, 8, 25},
    {{0}, 1, 8, 33},
    {{0}, 2, 48, 41},
    {{0}, 1, 8, 89},
    {{0}, 1, 2, 97},
};

pf2_3_v2_func_t g_func_pf2_3_v2 = {
    pf2_3_v2_pack,
    pf2_3_v2_unpack,
    pf2_3_v2_set_fields,
    pf2_3_v2_get_fields,
};

int pf1_1_v2_init(pf1_1_v2_t* cmp)
{
    if (!cmp) {
        return -1;
    }
    memset(cmp, 0, sizeof(pf1_1_v2_t));
    /* Initialize ipd1_f0 */
    cmp->ipd1_f0.num_val = 1;
    cmp->ipd1_f0.bit_width = 13;
    cmp->ipd1_f0.bit_offset = 0;
    /* Initialize ipd1_f1 */
    cmp->ipd1_f1.num_val = 1;
    cmp->ipd1_f1.bit_width = 14;
    cmp->ipd1_f1.bit_offset = 13;
    /* Initialize ipd1_f2 */
    cmp->ipd1_f2.num_val = 1;
    cmp->ipd1_f2.bit_width = 9;
    cmp->ipd1_f2.bit_offset = 27;
    /* Initialize ipd1_f3 */
    cmp->ipd1_f3.num_val = 1;
    cmp->ipd1_f3.bit_width = 4;
    cmp->ipd1_f3.bit_offset = 36;
    return 0;
}

int pf1_1_v2_pack(pf1_1_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=1, w_id=9, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    PACK_V2_FIELD(cmp->ipd1_f0, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f1, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f2, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f3, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf1_1_v2_unpack(pf1_1_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=1, w_id=9, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    UNPACK_V2_FIELD(cmp->ipd1_f0, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f1, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f2, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f3, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf1_1_v2_clear_fields(pf1_1_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmp->ipd1_f0.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f1.num_val; i++) {
        cmp->ipd1_f1.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmp->ipd1_f2.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmp->ipd1_f3.value[i] = 0;
    }
    return 0;
}

int pf1_1_v2_set_fields(pf1_1_v2_fields_t* cmf, pf1_1_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmp->ipd1_f0.value[i] = cmf->ipd1_f0[i];
    }
    for (i=0; i < cmp->ipd1_f1.num_val; i++) {
        cmp->ipd1_f1.value[i] = cmf->ipd1_f1[i];
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmp->ipd1_f2.value[i] = cmf->ipd1_f2[i];
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmp->ipd1_f3.value[i] = cmf->ipd1_f3[i];
    }
    return 0;
}

int pf1_1_v2_get_fields(pf1_1_v2_fields_t* cmf, pf1_1_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmf->ipd1_f0[i] = cmp->ipd1_f0.value[i];
    }
    for (i=0; i < cmp->ipd1_f1.num_val; i++) {
        cmf->ipd1_f1[i] = cmp->ipd1_f1.value[i];
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmf->ipd1_f2[i] = cmp->ipd1_f2.value[i];
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmf->ipd1_f3[i] = cmp->ipd1_f3.value[i];
    }
    return 0;
}

pf1_1_v2_t g_pf1_1_v2 = {
    {{0}, 1, 13, 0},
    {{0}, 1, 14, 13},
    {{0}, 1, 9, 27},
    {{0}, 1, 4, 36},
};

pf1_1_v2_func_t g_func_pf1_1_v2 = {
    pf1_1_v2_pack,
    pf1_1_v2_unpack,
    pf1_1_v2_set_fields,
    pf1_1_v2_get_fields,
};

int pf1_2_v2_init(pf1_2_v2_t* cmp)
{
    if (!cmp) {
        return -1;
    }
    memset(cmp, 0, sizeof(pf1_2_v2_t));
    /* Initialize ipd1_f4 */
    cmp->ipd1_f4.num_val = 1;
    cmp->ipd1_f4.bit_width = 16;
    cmp->ipd1_f4.bit_offset = 0;
    /* Initialize ipd1_f0 */
    cmp->ipd1_f0.num_val = 1;
    cmp->ipd1_f0.bit_width = 13;
    cmp->ipd1_f0.bit_offset = 16;
    /* Initialize ipd1_f1 */
    cmp->ipd1_f1.num_val = 1;
    cmp->ipd1_f1.bit_width = 14;
    cmp->ipd1_f1.bit_offset = 29;
    /* Initialize ipd1_f5 */
    cmp->ipd1_f5.num_val = 1;
    cmp->ipd1_f5.bit_width = 16;
    cmp->ipd1_f5.bit_offset = 43;
    /* Initialize ipd1_f2 */
    cmp->ipd1_f2.num_val = 1;
    cmp->ipd1_f2.bit_width = 9;
    cmp->ipd1_f2.bit_offset = 59;
    /* Initialize ipd1_f3 */
    cmp->ipd1_f3.num_val = 1;
    cmp->ipd1_f3.bit_width = 4;
    cmp->ipd1_f3.bit_offset = 68;
    return 0;
}

int pf1_2_v2_pack(pf1_2_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=1, w_id=9, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    PACK_V2_FIELD(cmp->ipd1_f4, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f0, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f1, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f5, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f2, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f3, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf1_2_v2_unpack(pf1_2_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=1, w_id=9, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    UNPACK_V2_FIELD(cmp->ipd1_f4, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f0, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f1, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f5, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f2, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f3, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf1_2_v2_clear_fields(pf1_2_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f4.num_val; i++) {
        cmp->ipd1_f4.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmp->ipd1_f0.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f1.num_val; i++) {
        cmp->ipd1_f1.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f5.num_val; i++) {
        cmp->ipd1_f5.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmp->ipd1_f2.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmp->ipd1_f3.value[i] = 0;
    }
    return 0;
}

int pf1_2_v2_set_fields(pf1_2_v2_fields_t* cmf, pf1_2_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f4.num_val; i++) {
        cmp->ipd1_f4.value[i] = cmf->ipd1_f4[i];
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmp->ipd1_f0.value[i] = cmf->ipd1_f0[i];
    }
    for (i=0; i < cmp->ipd1_f1.num_val; i++) {
        cmp->ipd1_f1.value[i] = cmf->ipd1_f1[i];
    }
    for (i=0; i < cmp->ipd1_f5.num_val; i++) {
        cmp->ipd1_f5.value[i] = cmf->ipd1_f5[i];
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmp->ipd1_f2.value[i] = cmf->ipd1_f2[i];
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmp->ipd1_f3.value[i] = cmf->ipd1_f3[i];
    }
    return 0;
}

int pf1_2_v2_get_fields(pf1_2_v2_fields_t* cmf, pf1_2_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f4.num_val; i++) {
        cmf->ipd1_f4[i] = cmp->ipd1_f4.value[i];
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmf->ipd1_f0[i] = cmp->ipd1_f0.value[i];
    }
    for (i=0; i < cmp->ipd1_f1.num_val; i++) {
        cmf->ipd1_f1[i] = cmp->ipd1_f1.value[i];
    }
    for (i=0; i < cmp->ipd1_f5.num_val; i++) {
        cmf->ipd1_f5[i] = cmp->ipd1_f5.value[i];
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmf->ipd1_f2[i] = cmp->ipd1_f2.value[i];
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmf->ipd1_f3[i] = cmp->ipd1_f3.value[i];
    }
    return 0;
}

pf1_2_v2_t g_pf1_2_v2 = {
    {{0}, 1, 16, 0},
    {{0}, 1, 13, 16},
    {{0}, 1, 14, 29},
    {{0}, 1, 16, 43},
    {{0}, 1, 9, 59},
    {{0}, 1, 4, 68},
};

pf1_2_v2_func_t g_func_pf1_2_v2 = {
    pf1_2_v2_pack,
    pf1_2_v2_unpack,
    pf1_2_v2_set_fields,
    pf1_2_v2_get_fields,
};

int pf1_3_v2_init(pf1_3_v2_t* cmp)
{
    if (!cmp) {
        return -1;
    }
    memset(cmp, 0, sizeof(pf1_3_v2_t));
    /* Initialize ipd1_f4 */
    cmp->ipd1_f4.num_val = 1;
    cmp->ipd1_f4.bit_width = 16;
    cmp->ipd1_f4.bit_offset = 0;
    /* Initialize ipd1_f0 */
    cmp->ipd1_f0.num_val = 1;
    cmp->ipd1_f0.bit_width = 13;
    cmp->ipd1_f0.bit_offset = 16;
    /* Initialize ipd1_f6 */
    cmp->ipd1_f6.num_val = 1;
    cmp->ipd1_f6.bit_width = 14;
    cmp->ipd1_f6.bit_offset = 29;
    /* Initialize ipd1_f2 */
    cmp->ipd1_f2.num_val = 1;
    cmp->ipd1_f2.bit_width = 9;
    cmp->ipd1_f2.bit_offset = 43;
    /* Initialize ipd1_f3 */
    cmp->ipd1_f3.num_val = 1;
    cmp->ipd1_f3.bit_width = 4;
    cmp->ipd1_f3.bit_offset = 52;
    return 0;
}

int pf1_3_v2_pack(pf1_3_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=1, w_id=9, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    PACK_V2_FIELD(cmp->ipd1_f4, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f0, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f6, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f2, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f3, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf1_3_v2_unpack(pf1_3_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=1, w_id=9, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    UNPACK_V2_FIELD(cmp->ipd1_f4, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f0, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f6, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f2, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f3, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf1_3_v2_clear_fields(pf1_3_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f4.num_val; i++) {
        cmp->ipd1_f4.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmp->ipd1_f0.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f6.num_val; i++) {
        cmp->ipd1_f6.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmp->ipd1_f2.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmp->ipd1_f3.value[i] = 0;
    }
    return 0;
}

int pf1_3_v2_set_fields(pf1_3_v2_fields_t* cmf, pf1_3_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f4.num_val; i++) {
        cmp->ipd1_f4.value[i] = cmf->ipd1_f4[i];
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmp->ipd1_f0.value[i] = cmf->ipd1_f0[i];
    }
    for (i=0; i < cmp->ipd1_f6.num_val; i++) {
        cmp->ipd1_f6.value[i] = cmf->ipd1_f6[i];
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmp->ipd1_f2.value[i] = cmf->ipd1_f2[i];
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmp->ipd1_f3.value[i] = cmf->ipd1_f3[i];
    }
    return 0;
}

int pf1_3_v2_get_fields(pf1_3_v2_fields_t* cmf, pf1_3_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f4.num_val; i++) {
        cmf->ipd1_f4[i] = cmp->ipd1_f4.value[i];
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmf->ipd1_f0[i] = cmp->ipd1_f0.value[i];
    }
    for (i=0; i < cmp->ipd1_f6.num_val; i++) {
        cmf->ipd1_f6[i] = cmp->ipd1_f6.value[i];
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmf->ipd1_f2[i] = cmp->ipd1_f2.value[i];
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmf->ipd1_f3[i] = cmp->ipd1_f3.value[i];
    }
    return 0;
}

pf1_3_v2_t g_pf1_3_v2 = {
    {{0}, 1, 16, 0},
    {{0}, 1, 13, 16},
    {{0}, 1, 14, 29},
    {{0}, 1, 9, 43},
    {{0}, 1, 4, 52},
};

pf1_3_v2_func_t g_func_pf1_3_v2 = {
    pf1_3_v2_pack,
    pf1_3_v2_unpack,
    pf1_3_v2_set_fields,
    pf1_3_v2_get_fields,
};

int pf1_4_v2_init(pf1_4_v2_t* cmp)
{
    if (!cmp) {
        return -1;
    }
    memset(cmp, 0, sizeof(pf1_4_v2_t));
    /* Initialize ipd1_f4 */
    cmp->ipd1_f4.num_val = 1;
    cmp->ipd1_f4.bit_width = 16;
    cmp->ipd1_f4.bit_offset = 0;
    /* Initialize ipd1_f0 */
    cmp->ipd1_f0.num_val = 1;
    cmp->ipd1_f0.bit_width = 13;
    cmp->ipd1_f0.bit_offset = 16;
    /* Initialize ipd1_f5 */
    cmp->ipd1_f5.num_val = 1;
    cmp->ipd1_f5.bit_width = 16;
    cmp->ipd1_f5.bit_offset = 29;
    /* Initialize ipd1_f6 */
    cmp->ipd1_f6.num_val = 1;
    cmp->ipd1_f6.bit_width = 14;
    cmp->ipd1_f6.bit_offset = 45;
    /* Initialize ipd1_f2 */
    cmp->ipd1_f2.num_val = 1;
    cmp->ipd1_f2.bit_width = 9;
    cmp->ipd1_f2.bit_offset = 59;
    /* Initialize ipd1_f3 */
    cmp->ipd1_f3.num_val = 1;
    cmp->ipd1_f3.bit_width = 4;
    cmp->ipd1_f3.bit_offset = 68;
    return 0;
}

int pf1_4_v2_pack(pf1_4_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=1, w_id=9, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    PACK_V2_FIELD(cmp->ipd1_f4, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f0, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f5, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f6, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f2, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f3, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf1_4_v2_unpack(pf1_4_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=1, w_id=9, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    UNPACK_V2_FIELD(cmp->ipd1_f4, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f0, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f5, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f6, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f2, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f3, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf1_4_v2_clear_fields(pf1_4_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f4.num_val; i++) {
        cmp->ipd1_f4.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmp->ipd1_f0.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f5.num_val; i++) {
        cmp->ipd1_f5.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f6.num_val; i++) {
        cmp->ipd1_f6.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmp->ipd1_f2.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmp->ipd1_f3.value[i] = 0;
    }
    return 0;
}

int pf1_4_v2_set_fields(pf1_4_v2_fields_t* cmf, pf1_4_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f4.num_val; i++) {
        cmp->ipd1_f4.value[i] = cmf->ipd1_f4[i];
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmp->ipd1_f0.value[i] = cmf->ipd1_f0[i];
    }
    for (i=0; i < cmp->ipd1_f5.num_val; i++) {
        cmp->ipd1_f5.value[i] = cmf->ipd1_f5[i];
    }
    for (i=0; i < cmp->ipd1_f6.num_val; i++) {
        cmp->ipd1_f6.value[i] = cmf->ipd1_f6[i];
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmp->ipd1_f2.value[i] = cmf->ipd1_f2[i];
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmp->ipd1_f3.value[i] = cmf->ipd1_f3[i];
    }
    return 0;
}

int pf1_4_v2_get_fields(pf1_4_v2_fields_t* cmf, pf1_4_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f4.num_val; i++) {
        cmf->ipd1_f4[i] = cmp->ipd1_f4.value[i];
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmf->ipd1_f0[i] = cmp->ipd1_f0.value[i];
    }
    for (i=0; i < cmp->ipd1_f5.num_val; i++) {
        cmf->ipd1_f5[i] = cmp->ipd1_f5.value[i];
    }
    for (i=0; i < cmp->ipd1_f6.num_val; i++) {
        cmf->ipd1_f6[i] = cmp->ipd1_f6.value[i];
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmf->ipd1_f2[i] = cmp->ipd1_f2.value[i];
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmf->ipd1_f3[i] = cmp->ipd1_f3.value[i];
    }
    return 0;
}

pf1_4_v2_t g_pf1_4_v2 = {
    {{0}, 1, 16, 0},
    {{0}, 1, 13, 16},
    {{0}, 1, 16, 29},
    {{0}, 1, 14, 45},
    {{0}, 1, 9, 59},
    {{0}, 1, 4, 68},
};

pf1_4_v2_func_t g_func_pf1_4_v2 = {
    pf1_4_v2_pack,
    pf1_4_v2_unpack,
    pf1_4_v2_set_fields,
    pf1_4_v2_get_fields,
};

int pf1_5_v2_init(pf1_5_v2_t* cmp)
{
    if (!cmp) {
        return -1;
    }
    memset(cmp, 0, sizeof(pf1_5_v2_t));
    /* Initialize ipd1_f7 */
    cmp->ipd1_f7.num_val = 1;
    cmp->ipd1_f7.bit_width = 17;
    cmp->ipd1_f7.bit_offset = 0;
    /* Initialize ipd1_f8 */
    cmp->ipd1_f8.num_val = 1;
    cmp->ipd1_f8.bit_width = 3;
    cmp->ipd1_f8.bit_offset = 17;
    /* Initialize ipd1_f0 */
    cmp->ipd1_f0.num_val = 1;
    cmp->ipd1_f0.bit_width = 13;
    cmp->ipd1_f0.bit_offset = 20;
    /* Initialize ipd1_f1 */
    cmp->ipd1_f1.num_val = 1;
    cmp->ipd1_f1.bit_width = 14;
    cmp->ipd1_f1.bit_offset = 33;
    /* Initialize ipd1_f2 */
    cmp->ipd1_f2.num_val = 1;
    cmp->ipd1_f2.bit_width = 9;
    cmp->ipd1_f2.bit_offset = 47;
    /* Initialize ipd1_f3 */
    cmp->ipd1_f3.num_val = 1;
    cmp->ipd1_f3.bit_width = 4;
    cmp->ipd1_f3.bit_offset = 56;
    return 0;
}

int pf1_5_v2_pack(pf1_5_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=1, w_id=9, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    PACK_V2_FIELD(cmp->ipd1_f7, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f8, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f0, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f1, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f2, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f3, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf1_5_v2_unpack(pf1_5_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=1, w_id=9, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    UNPACK_V2_FIELD(cmp->ipd1_f7, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f8, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f0, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f1, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f2, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f3, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf1_5_v2_clear_fields(pf1_5_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f7.num_val; i++) {
        cmp->ipd1_f7.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f8.num_val; i++) {
        cmp->ipd1_f8.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmp->ipd1_f0.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f1.num_val; i++) {
        cmp->ipd1_f1.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmp->ipd1_f2.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmp->ipd1_f3.value[i] = 0;
    }
    return 0;
}

int pf1_5_v2_set_fields(pf1_5_v2_fields_t* cmf, pf1_5_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f7.num_val; i++) {
        cmp->ipd1_f7.value[i] = cmf->ipd1_f7[i];
    }
    for (i=0; i < cmp->ipd1_f8.num_val; i++) {
        cmp->ipd1_f8.value[i] = cmf->ipd1_f8[i];
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmp->ipd1_f0.value[i] = cmf->ipd1_f0[i];
    }
    for (i=0; i < cmp->ipd1_f1.num_val; i++) {
        cmp->ipd1_f1.value[i] = cmf->ipd1_f1[i];
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmp->ipd1_f2.value[i] = cmf->ipd1_f2[i];
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmp->ipd1_f3.value[i] = cmf->ipd1_f3[i];
    }
    return 0;
}

int pf1_5_v2_get_fields(pf1_5_v2_fields_t* cmf, pf1_5_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f7.num_val; i++) {
        cmf->ipd1_f7[i] = cmp->ipd1_f7.value[i];
    }
    for (i=0; i < cmp->ipd1_f8.num_val; i++) {
        cmf->ipd1_f8[i] = cmp->ipd1_f8.value[i];
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmf->ipd1_f0[i] = cmp->ipd1_f0.value[i];
    }
    for (i=0; i < cmp->ipd1_f1.num_val; i++) {
        cmf->ipd1_f1[i] = cmp->ipd1_f1.value[i];
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmf->ipd1_f2[i] = cmp->ipd1_f2.value[i];
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmf->ipd1_f3[i] = cmp->ipd1_f3.value[i];
    }
    return 0;
}

pf1_5_v2_t g_pf1_5_v2 = {
    {{0}, 1, 17, 0},
    {{0}, 1, 3, 17},
    {{0}, 1, 13, 20},
    {{0}, 1, 14, 33},
    {{0}, 1, 9, 47},
    {{0}, 1, 4, 56},
};

pf1_5_v2_func_t g_func_pf1_5_v2 = {
    pf1_5_v2_pack,
    pf1_5_v2_unpack,
    pf1_5_v2_set_fields,
    pf1_5_v2_get_fields,
};

int pf1_6_v2_init(pf1_6_v2_t* cmp)
{
    if (!cmp) {
        return -1;
    }
    memset(cmp, 0, sizeof(pf1_6_v2_t));
    /* Initialize ipd1_f7 */
    cmp->ipd1_f7.num_val = 1;
    cmp->ipd1_f7.bit_width = 17;
    cmp->ipd1_f7.bit_offset = 0;
    /* Initialize ipd1_f8 */
    cmp->ipd1_f8.num_val = 1;
    cmp->ipd1_f8.bit_width = 3;
    cmp->ipd1_f8.bit_offset = 17;
    /* Initialize ipd1_f0 */
    cmp->ipd1_f0.num_val = 1;
    cmp->ipd1_f0.bit_width = 13;
    cmp->ipd1_f0.bit_offset = 20;
    /* Initialize ipd1_f1 */
    cmp->ipd1_f1.num_val = 1;
    cmp->ipd1_f1.bit_width = 14;
    cmp->ipd1_f1.bit_offset = 33;
    /* Initialize ipd1_f6 */
    cmp->ipd1_f6.num_val = 1;
    cmp->ipd1_f6.bit_width = 14;
    cmp->ipd1_f6.bit_offset = 47;
    /* Initialize ipd1_f9 */
    cmp->ipd1_f9.num_val = 1;
    cmp->ipd1_f9.bit_width = 12;
    cmp->ipd1_f9.bit_offset = 61;
    /* Initialize ipd1_f2 */
    cmp->ipd1_f2.num_val = 1;
    cmp->ipd1_f2.bit_width = 9;
    cmp->ipd1_f2.bit_offset = 73;
    /* Initialize ipd1_f3 */
    cmp->ipd1_f3.num_val = 1;
    cmp->ipd1_f3.bit_width = 4;
    cmp->ipd1_f3.bit_offset = 82;
    return 0;
}

int pf1_6_v2_pack(pf1_6_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=1, w_id=9, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    PACK_V2_FIELD(cmp->ipd1_f7, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f8, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f0, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f1, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f6, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f9, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f2, w_id, b_id, bm, mk_msb);
    PACK_V2_FIELD(cmp->ipd1_f3, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf1_6_v2_unpack(pf1_6_v2_t* cmp, uint8_t * bm)
{
    uint32_t mk_msb=1, w_id=9, b_id=0;
    if (!cmp) {
        return -1;
    }
    if (!bm) {
        return -1;
    }
    UNPACK_V2_FIELD(cmp->ipd1_f7, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f8, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f0, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f1, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f6, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f9, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f2, w_id, b_id, bm, mk_msb);
    UNPACK_V2_FIELD(cmp->ipd1_f3, w_id, b_id, bm, mk_msb);
    return 0;
}

int pf1_6_v2_clear_fields(pf1_6_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f7.num_val; i++) {
        cmp->ipd1_f7.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f8.num_val; i++) {
        cmp->ipd1_f8.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmp->ipd1_f0.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f1.num_val; i++) {
        cmp->ipd1_f1.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f6.num_val; i++) {
        cmp->ipd1_f6.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f9.num_val; i++) {
        cmp->ipd1_f9.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmp->ipd1_f2.value[i] = 0;
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmp->ipd1_f3.value[i] = 0;
    }
    return 0;
}

int pf1_6_v2_set_fields(pf1_6_v2_fields_t* cmf, pf1_6_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f7.num_val; i++) {
        cmp->ipd1_f7.value[i] = cmf->ipd1_f7[i];
    }
    for (i=0; i < cmp->ipd1_f8.num_val; i++) {
        cmp->ipd1_f8.value[i] = cmf->ipd1_f8[i];
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmp->ipd1_f0.value[i] = cmf->ipd1_f0[i];
    }
    for (i=0; i < cmp->ipd1_f1.num_val; i++) {
        cmp->ipd1_f1.value[i] = cmf->ipd1_f1[i];
    }
    for (i=0; i < cmp->ipd1_f6.num_val; i++) {
        cmp->ipd1_f6.value[i] = cmf->ipd1_f6[i];
    }
    for (i=0; i < cmp->ipd1_f9.num_val; i++) {
        cmp->ipd1_f9.value[i] = cmf->ipd1_f9[i];
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmp->ipd1_f2.value[i] = cmf->ipd1_f2[i];
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmp->ipd1_f3.value[i] = cmf->ipd1_f3[i];
    }
    return 0;
}

int pf1_6_v2_get_fields(pf1_6_v2_fields_t* cmf, pf1_6_v2_t* cmp)
{
    uint32_t i;
    if (!cmp) {
        return -1;
    }
    for (i=0; i < cmp->ipd1_f7.num_val; i++) {
        cmf->ipd1_f7[i] = cmp->ipd1_f7.value[i];
    }
    for (i=0; i < cmp->ipd1_f8.num_val; i++) {
        cmf->ipd1_f8[i] = cmp->ipd1_f8.value[i];
    }
    for (i=0; i < cmp->ipd1_f0.num_val; i++) {
        cmf->ipd1_f0[i] = cmp->ipd1_f0.value[i];
    }
    for (i=0; i < cmp->ipd1_f1.num_val; i++) {
        cmf->ipd1_f1[i] = cmp->ipd1_f1.value[i];
    }
    for (i=0; i < cmp->ipd1_f6.num_val; i++) {
        cmf->ipd1_f6[i] = cmp->ipd1_f6.value[i];
    }
    for (i=0; i < cmp->ipd1_f9.num_val; i++) {
        cmf->ipd1_f9[i] = cmp->ipd1_f9.value[i];
    }
    for (i=0; i < cmp->ipd1_f2.num_val; i++) {
        cmf->ipd1_f2[i] = cmp->ipd1_f2.value[i];
    }
    for (i=0; i < cmp->ipd1_f3.num_val; i++) {
        cmf->ipd1_f3[i] = cmp->ipd1_f3.value[i];
    }
    return 0;
}

pf1_6_v2_t g_pf1_6_v2 = {
    {{0}, 1, 17, 0},
    {{0}, 1, 3, 17},
    {{0}, 1, 13, 20},
    {{0}, 1, 14, 33},
    {{0}, 1, 14, 47},
    {{0}, 1, 12, 61},
    {{0}, 1, 9, 73},
    {{0}, 1, 4, 82},
};

pf1_6_v2_func_t g_func_pf1_6_v2 = {
    pf1_6_v2_pack,
    pf1_6_v2_unpack,
    pf1_6_v2_set_fields,
    pf1_6_v2_get_fields,
};

int inno_unpack_cmhdr_v2(uint8_t * buf, ipd_fields_v2_t * ipdfld_p)
{
    cfx_v2_t cmf;
    int rc;
    if (!buf || !ipdfld_p)
        return -1;
    memset(ipdfld_p, 0, sizeof(ipd_fields_v2_t));
    rc = cfx_v2_init(&cmf);
    if (rc != 0)
        return rc;
    rc = cfx_v2_unpack(&cmf, buf);
    if (rc != 0)
        return rc;
    ipdfld_p->e1 = cmf.ipd_f14.value[0];
    ipdfld_p->e2 = cmf.ipd_f15.value[0];
    switch (ipdfld_p->e1 + 1) {
        case 1:
        {
            pf1_1_v2_t pf1_1;
            rc = pf1_1_v2_init(&pf1_1);
            if (rc != 0)
                return rc;
            rc = pf1_1_v2_unpack(&pf1_1, buf);
            if (rc != 0)
                return rc;
            ipdfld_p->vni = pf1_1.ipd1_f0.value[0];
        }
        break;
        case 2:
        {
            pf1_2_v2_t pf1_2;
            rc = pf1_2_v2_init(&pf1_2);
            if (rc != 0)
                return rc;
            rc = pf1_2_v2_unpack(&pf1_2, buf);
            if (rc != 0)
                return rc;
            ipdfld_p->vni = pf1_2.ipd1_f0.value[0];
        }
        break;
        case 3:
        {
            pf1_3_v2_t pf1_3;
            rc = pf1_3_v2_init(&pf1_3);
            if (rc != 0)
                return rc;
            rc = pf1_3_v2_unpack(&pf1_3, buf);
            if (rc != 0)
                return rc;
            ipdfld_p->vni = pf1_3.ipd1_f0.value[0];
            ipdfld_p->l3iif = pf1_3.ipd1_f6.value[0];
        }
        break;
        case 4:
        {
            pf1_4_v2_t pf1_4;
            rc = pf1_4_v2_init(&pf1_4);
            if (rc != 0)
                return rc;
            rc = pf1_4_v2_unpack(&pf1_4, buf);
            if (rc != 0)
                return rc;
            ipdfld_p->vni = pf1_4.ipd1_f0.value[0];
            ipdfld_p->l3iif = pf1_4.ipd1_f6.value[0];
        }
        break;
        case 5:
        {
            pf1_5_v2_t pf1_5;
            rc = pf1_5_v2_init(&pf1_5);
            if (rc != 0)
                return rc;
            rc = pf1_5_v2_unpack(&pf1_5, buf);
            if (rc != 0)
                return rc;
            ipdfld_p->vni = pf1_5.ipd1_f0.value[0];
        }
        break;
        case 6:
        {
            pf1_6_v2_t pf1_6;
            rc = pf1_6_v2_init(&pf1_6);
            if (rc != 0)
                return rc;
            rc = pf1_6_v2_unpack(&pf1_6, buf);
            if (rc != 0)
                return rc;
            ipdfld_p->vni = pf1_6.ipd1_f0.value[0];
            ipdfld_p->l3iif = pf1_6.ipd1_f6.value[0];
        }
        break;
        default:
            break;
    }
    switch (ipdfld_p->e2 + 1) {
        case 1:
        {
            pf2_1_v2_t pf2_1;
            rc = pf2_1_v2_init(&pf2_1);
            if (rc != 0)
                return rc;
            rc = pf2_1_v2_unpack(&pf2_1, buf);
            if (rc != 0)
                return rc;
            ipdfld_p->ttl = pf2_1.ipd2_f0.value[0];
        }
        break;
        case 2:
        {
            pf2_2_v2_t pf2_2;
            rc = pf2_2_v2_init(&pf2_2);
            if (rc != 0)
                return rc;
            rc = pf2_2_v2_unpack(&pf2_2, buf);
            if (rc != 0)
                return rc;
            ipdfld_p->ttl = pf2_2.ipd2_f0.value[0];
        }
        break;
        case 3:
        {
            pf2_3_v2_t pf2_3;
            rc = pf2_3_v2_init(&pf2_3);
            if (rc != 0)
                return rc;
            rc = pf2_3_v2_unpack(&pf2_3, buf);
            if (rc != 0)
                return rc;
            ipdfld_p->ttl = pf2_3.ipd2_f0.value[0];
        }
        break;
        default:
            break;
    }
    return 0;
}
